# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egyenlet.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QTextEdit
from sympy import *
from numpy import *
import sys


class Ui_Egyenlet(object):
    def extract_variable(self, expression):
        valtozok = []

        for i in expression:
            if i not in valtozok and i.isalpha():
                valtozok.append(i.lower())

        return valtozok
    
    def number_of_lines(self, expression):
        res = []
        number = 0

        for line in expression.splitlines():
                if line.strip():
                    number += 1
                    res.append(line)

        res.append(number)
        return res
    
    def write_res(self, res):
        result = "y = "
        for i in res:
            for j in i:
                if not len(str(j)) == 1:
                    expression = str(j).replace('I', '1j')
                    
                    result += str(round(eval(expression), 2)) + " "
                    print(str(eval(expression)))

        return result.strip()
    
    def write_res_list(self, res):
        result = ""
        for i in res:
            expression = str(i).replace('I', '1j')
            
            result += str(round(eval(expression), 2)) + " "
            print(str(round(eval(expression), 2)))

        #print("'{}'".format(result))
        #print("'{}'".format(result.rstrip(" | ")))
        return result.strip()

    def is_fractional_equation(self, equation):
        if '/' in equation or '.' in equation:
            return True
        else:
            return False

    def one_func(self, one_func, replaced_func):
        try:
                splitted_func = one_func.replace(" ", "").split("=")
                symbs = self.extract_variable(replaced_func)
                print(symbs)

                equation = Eq(sympify(splitted_func[0]), sympify(splitted_func[1]) )

                rearranged_equation = equation.lhs - equation.rhs
                result = solve(rearranged_equation, tuple(symbs))
                
                if len(symbs) == 1:
                    if (len(result) >= 2 ):
                        self.label_2.setText(self.write_res_list(result))
                    else:
                        self.label_2.setText(self.write_res_list(result).replace("**", "^"))
                else:
                    self.label_2.setText(self.write_res(result).replace("**", "^"))
        except Exception as x:
            print(x)
            self.label_2.setText("Helytelen egyenlet!")     

    def combobox_selector(self):
        input_text = self.comboBox.currentText()
        function_text = self.text_edit.toPlainText().lower()
        number_of_rows = self.number_of_lines(function_text)

        if input_text == "Egyenlet":
            if len(number_of_rows) == 2 :
                self.one_func(function_text, function_text.replace("sqrt", ""))
            else:
                self.label_2.setText("Egy sort adj meg")
                self.text_edit.setText("")

    def setupUi(self, Egyenlet, MainWindow):
        Egyenlet.setObjectName("Egyenlet")
        Egyenlet.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Egyenlet)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 70, 291, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 781, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")


        self.pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.combobox_selector())
        self.pushButton.setGeometry(QtCore.QRect(710, 70, 75, 51))
        self.pushButton.setObjectName("pushButton")

        self.text_edit = QTextEdit(self.centralwidget)
        self.text_edit.setGeometry(310, 20, 391, 101)
        self.text_edit.setObjectName("text_edit")

        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(250, 10, 391, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        Egyenlet.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Egyenlet)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Egyenlet.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Egyenlet)
        self.statusbar.setObjectName("statusbar")
        Egyenlet.setStatusBar(self.statusbar)

        self.retranslateUi(Egyenlet)
        QtCore.QMetaObject.connectSlotsByName(Egyenlet)

    def retranslateUi(self, Egyenlet):
        _translate = QtCore.QCoreApplication.translate
        Egyenlet.setWindowTitle(_translate("Egyenlet", "Egyenlet"))
        self.comboBox.setItemText(0, _translate("Egyenlet", "Egyenlet"))
        self.comboBox.setItemText(1, _translate("Egyenlet", "Trigonometrikus"))
        self.comboBox.setItemText(2, _translate("Egyenlet", "Paraméteres"))
        self.comboBox.setItemText(3, _translate("Egyenlet", "Lineáris egyenletrendszerek"))
        self.comboBox.setItemText(4, _translate("Egyenlet", "Nem lineáris egyenletrendszerek"))
        self.label.setText(_translate("Egyenlet", "Válaszd ki a végrahajtandó műveletet"))
        self.label_2.setText(_translate("Egyenlet", "Eredmény"))
        self.pushButton.setText(_translate("Egyenlet", "Enter"))
        self.label_3.setText(_translate("Egyenlet", "Egyenlet"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Egyenlet = QtWidgets.QMainWindow()
    ui = Ui_Egyenlet()
    ui.setupUi(Egyenlet)
    Egyenlet.show()
    sys.exit(app.exec_())
