# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Programmer_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Programmer_calc(object):
    def applyStylesheet(self, Programmer_calc):
        style_sheet = """
        QMainWindow {
            background-color: #2E2E2E;
        }
        QtWidgets.QGridLayout{
            background-color: #ff0000
        }
        QLabel#outputLabel {
            background-color: #1C1C1C;
            color: #FFFFFF;
            border: 2px solid #555555;
            border-radius: 5px;
            padding: 10px;
        }
        QPushButton {
            background-color: #4E4E4E;
            color: #FFFFFF;
            border: 1px solid #555555;
            border-radius: 10px;
            padding: 10px;
        }
        QPushButton:hover {
            background-color: #5E5E5E;
        }
        QPushButton:pressed {
            background-color: #6E6E6E;
        }
        QComboBox {
            background-color: #4E4E4E;
            color: #FFFFFF;
            border: 1px solid #555555;
            border-radius: 5px;
            padding: 5px;
        }
        QComboBox QAbstractItemView {
            background-color: #4E4E4E;
            selection-background-color: #5E5E5E;
            color: #FFFFFF;
        }
        QToolBar {
            background-color: #3E3E3E;
            border: none;
        }
        """
        Programmer_calc.setStyleSheet(style_sheet)

    def back_to_mainwindow(self, Egyenlet, MainWindow):
        Egyenlet.close()
        MainWindow.show()

    def setupUi(self, Programmer_calc, MainWindow):
        self.applyStylesheet(Programmer_calc)
        Programmer_calc.setObjectName("Programmer_calc")
        Programmer_calc.resize(1083, 748)
        Programmer_calc.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(Programmer_calc)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 50, 1051, 91))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Result = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        self.Result.setFont(font)
        self.Result.setObjectName("Result")
        self.verticalLayout_2.addWidget(self.Result)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 1051, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Back = QtWidgets.QPushButton(
            self.centralwidget,
            clicked=lambda: self.back_to_mainwindow(Programmer_calc, MainWindow),
        )
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.Back.setFont(font)
        self.Back.setObjectName("Back")
        self.horizontalLayout.addWidget(self.Back)
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 180, 1051, 211))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.n8_63 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.n8_63.setObjectName("n8_63")
        self.verticalLayout.addWidget(self.n8_63)
        self.h2_47 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.h2_47.setObjectName("h2_47")
        self.verticalLayout.addWidget(self.h2_47)
        self.t6_31 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.t6_31.setObjectName("t6_31")
        self.verticalLayout.addWidget(self.t6_31)
        self.nulla_15 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.nulla_15.setObjectName("nulla_15")
        self.verticalLayout.addWidget(self.nulla_15)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 140, 1051, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        spacerItem1 = QtWidgets.QSpacerItem(
            700, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(10, 390, 1051, 311))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout_for_numbers = QtWidgets.QGridLayout()
        self.gridLayout_for_numbers.setObjectName("gridLayout_for_numbers")
        self.bel_zj = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.bel_zj.setObjectName("bel_zj")
        self.gridLayout_for_numbers.addWidget(self.bel_zj, 0, 1, 1, 1)
        self.eight = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.eight.setObjectName("eight")
        self.gridLayout_for_numbers.addWidget(self.eight, 3, 0, 1, 1)
        self.D_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.D_hex.setObjectName("D_hex")
        self.gridLayout_for_numbers.addWidget(self.D_hex, 1, 1, 1, 1)
        self.C_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.C_hex.setObjectName("C_hex")
        self.gridLayout_for_numbers.addWidget(self.C_hex, 1, 0, 1, 1)
        self.three = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.three.setObjectName("three")
        self.gridLayout_for_numbers.addWidget(self.three, 5, 3, 1, 1)
        self.minus = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.minus.setObjectName("minus")
        self.gridLayout_for_numbers.addWidget(self.minus, 4, 4, 1, 1)
        self.dot = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.dot.setObjectName("dot")
        self.gridLayout_for_numbers.addWidget(self.dot, 3, 5, 1, 1)
        self.B_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.B_hex.setObjectName("B_hex")
        self.gridLayout_for_numbers.addWidget(self.B_hex, 3, 3, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.clear = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.clear.setObjectName("clear")
        self.verticalLayout_4.addWidget(self.clear)
        self.gridLayout_for_numbers.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.four = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.four.setObjectName("four")
        self.gridLayout_for_numbers.addWidget(self.four, 4, 0, 1, 1)
        self.jobb_zj = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.jobb_zj.setObjectName("jobb_zj")
        self.gridLayout_for_numbers.addWidget(self.jobb_zj, 0, 2, 1, 1)
        self.one = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.one.setObjectName("one")
        self.gridLayout_for_numbers.addWidget(self.one, 5, 1, 1, 1)
        self.nine = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.nine.setObjectName("nine")
        self.gridLayout_for_numbers.addWidget(self.nine, 3, 1, 1, 1)
        self.mod = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.mod.setObjectName("mod")
        self.gridLayout_for_numbers.addWidget(self.mod, 0, 3, 1, 1)
        self.A_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.A_hex.setObjectName("A_hex")
        self.gridLayout_for_numbers.addWidget(self.A_hex, 3, 2, 1, 1)
        self.zero = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.zero.setObjectName("zero")
        self.gridLayout_for_numbers.addWidget(self.zero, 5, 0, 1, 1)
        self.two = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.two.setObjectName("two")
        self.gridLayout_for_numbers.addWidget(self.two, 5, 2, 1, 1)
        self.six = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.six.setObjectName("six")
        self.gridLayout_for_numbers.addWidget(self.six, 4, 2, 1, 1)
        self.F_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.F_hex.setObjectName("F_hex")
        self.gridLayout_for_numbers.addWidget(self.F_hex, 1, 3, 1, 1)
        self.plusz = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.plusz.setObjectName("plusz")
        self.gridLayout_for_numbers.addWidget(self.plusz, 5, 4, 1, 1)
        self.seven = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.seven.setObjectName("seven")
        self.gridLayout_for_numbers.addWidget(self.seven, 4, 3, 1, 1)
        self.equal = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.equal.setObjectName("equal")
        self.gridLayout_for_numbers.addWidget(self.equal, 4, 5, 2, 1)
        self.five = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.five.setObjectName("five")
        self.gridLayout_for_numbers.addWidget(self.five, 4, 1, 1, 1)
        self.divide = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.divide.setObjectName("divide")
        self.gridLayout_for_numbers.addWidget(self.divide, 1, 4, 1, 1)
        self.szorzas = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.szorzas.setObjectName("szorzas")
        self.gridLayout_for_numbers.addWidget(self.szorzas, 3, 4, 1, 1)
        self.sqrt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.sqrt.setObjectName("sqrt")
        self.gridLayout_for_numbers.addWidget(self.sqrt, 1, 5, 1, 1)
        self.E_hex = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.E_hex.setObjectName("E_hex")
        self.gridLayout_for_numbers.addWidget(self.E_hex, 1, 2, 1, 1)
        self.pi = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.pi.setObjectName("pi")
        self.gridLayout_for_numbers.addWidget(self.pi, 0, 4, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_for_numbers)
        self.gridLayout_for_special_buttons = QtWidgets.QGridLayout()
        self.gridLayout_for_special_buttons.setObjectName(
            "gridLayout_for_special_buttons"
        )
        self.frac = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.frac.setObjectName("frac")
        self.gridLayout_for_special_buttons.addWidget(self.frac, 3, 2, 1, 1)
        self.fakt = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.fakt.setObjectName("fakt")
        self.gridLayout_for_special_buttons.addWidget(self.fakt, 3, 0, 1, 1)
        self.XOR = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.XOR.setObjectName("XOR")
        self.gridLayout_for_special_buttons.addWidget(self.XOR, 0, 4, 1, 1)
        self.plusn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.plusn.setObjectName("plusn")
        self.gridLayout_for_special_buttons.addWidget(self.plusn, 0, 0, 1, 1)
        self.abs = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.abs.setObjectName("abs")
        self.gridLayout_for_special_buttons.addWidget(self.abs, 3, 1, 1, 1)
        self.NOT = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.NOT.setObjectName("NOT")
        self.gridLayout_for_special_buttons.addWidget(self.NOT, 1, 2, 1, 1)
        self.log = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.log.setObjectName("log")
        self.gridLayout_for_special_buttons.addWidget(self.log, 2, 4, 1, 1)
        self.x_xx_y = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.x_xx_y.setObjectName("x_xx_y")
        self.gridLayout_for_special_buttons.addWidget(self.x_xx_y, 2, 0, 1, 1)
        self.minusn = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.minusn.setObjectName("minusn")
        self.gridLayout_for_special_buttons.addWidget(self.minusn, 0, 1, 1, 1)
        self.ones = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.ones.setObjectName("ones")
        self.gridLayout_for_special_buttons.addWidget(self.ones, 1, 0, 1, 1)
        self.int_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.int_2.setObjectName("int_2")
        self.gridLayout_for_special_buttons.addWidget(self.int_2, 2, 2, 1, 1)
        self.x_xx_1 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.x_xx_1.setObjectName("x_xx_1")
        self.gridLayout_for_special_buttons.addWidget(self.x_xx_1, 2, 1, 1, 1)
        self.twos = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.twos.setObjectName("twos")
        self.gridLayout_for_special_buttons.addWidget(self.twos, 1, 1, 1, 1)
        self.AND = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.AND.setObjectName("AND")
        self.gridLayout_for_special_buttons.addWidget(self.AND, 1, 3, 1, 1)
        self.variable_name = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.variable_name.setObjectName("variable_name")
        self.variable_name.addItem("")
        self.gridLayout_for_special_buttons.addWidget(self.variable_name, 4, 0, 1, 2)
        self.log2 = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.log2.setObjectName("log2")
        self.gridLayout_for_special_buttons.addWidget(self.log2, 2, 3, 1, 1)
        self.OR = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.OR.setObjectName("OR")
        self.gridLayout_for_special_buttons.addWidget(self.OR, 1, 4, 1, 1)
        self.shift_left = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.shift_left.setObjectName("shift_left")
        self.shift_left.addItem("")
        self.gridLayout_for_special_buttons.addWidget(self.shift_left, 0, 2, 1, 1)
        self.shift_right = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.shift_right.setObjectName("shift_right")
        self.shift_right.addItem("")
        self.gridLayout_for_special_buttons.addWidget(self.shift_right, 0, 3, 1, 1)
        self.aaaa = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.aaaa.setObjectName("aaaa")
        self.gridLayout_for_special_buttons.addWidget(self.aaaa, 3, 3, 1, 2)
        self.fact = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.fact.setObjectName("fact")
        self.gridLayout_for_special_buttons.addWidget(self.fact, 4, 2, 1, 1)
        self.variable_name_2 = QtWidgets.QComboBox(self.horizontalLayoutWidget_3)
        self.variable_name_2.setObjectName("variable_name_2")
        self.variable_name_2.addItem("")
        self.gridLayout_for_special_buttons.addWidget(self.variable_name_2, 4, 3, 1, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_for_special_buttons)
        Programmer_calc.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Programmer_calc)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 21))
        self.menubar.setObjectName("menubar")
        Programmer_calc.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Programmer_calc)
        self.statusbar.setObjectName("statusbar")
        Programmer_calc.setStatusBar(self.statusbar)

        self.retranslateUi(Programmer_calc)
        QtCore.QMetaObject.connectSlotsByName(Programmer_calc)

    def retranslateUi(self, Programmer_calc):
        _translate = QtCore.QCoreApplication.translate
        Programmer_calc.setWindowTitle(_translate("Programmer_calc", "MainWindow"))
        self.Result.setText(_translate("Programmer_calc", "Eredmény"))
        self.Back.setText(_translate("Programmer_calc", "Vissza"))
        self.n8_63.setText(_translate("Programmer_calc", "TextLabel"))
        self.h2_47.setText(_translate("Programmer_calc", "TextLabel"))
        self.t6_31.setText(_translate("Programmer_calc", "TextLabel"))
        self.nulla_15.setText(_translate("Programmer_calc", "TextLabel"))
        self.comboBox_3.setItemText(0, _translate("Programmer_calc", "Decimális"))
        self.label_2.setText(_translate("Programmer_calc", "x fok = y radián"))
        self.bel_zj.setText(_translate("Programmer_calc", "("))
        self.eight.setText(_translate("Programmer_calc", "8"))
        self.D_hex.setText(_translate("Programmer_calc", "D"))
        self.C_hex.setText(_translate("Programmer_calc", "C"))
        self.three.setText(_translate("Programmer_calc", "3"))
        self.minus.setText(_translate("Programmer_calc", "-"))
        self.dot.setText(_translate("Programmer_calc", "."))
        self.B_hex.setText(_translate("Programmer_calc", "B"))
        self.clear.setText(_translate("Programmer_calc", "C"))
        self.four.setText(_translate("Programmer_calc", "4"))
        self.jobb_zj.setText(_translate("Programmer_calc", ")"))
        self.one.setText(_translate("Programmer_calc", "1"))
        self.nine.setText(_translate("Programmer_calc", "9"))
        self.mod.setText(_translate("Programmer_calc", "mod"))
        self.A_hex.setText(_translate("Programmer_calc", "C"))
        self.zero.setText(_translate("Programmer_calc", "0"))
        self.two.setText(_translate("Programmer_calc", "2"))
        self.six.setText(_translate("Programmer_calc", "6"))
        self.F_hex.setText(_translate("Programmer_calc", "F"))
        self.plusz.setText(_translate("Programmer_calc", "+"))
        self.seven.setText(_translate("Programmer_calc", "7"))
        self.equal.setText(_translate("Programmer_calc", "="))
        self.five.setText(_translate("Programmer_calc", "5"))
        self.divide.setText(_translate("Programmer_calc", "/"))
        self.szorzas.setText(_translate("Programmer_calc", "x"))
        self.sqrt.setText(_translate("Programmer_calc", "sqrt"))
        self.E_hex.setText(_translate("Programmer_calc", "E"))
        self.pi.setText(_translate("Programmer_calc", "pi"))
        self.frac.setText(_translate("Programmer_calc", "frac"))
        self.fakt.setText(_translate("Programmer_calc", "x!"))
        self.XOR.setText(_translate("Programmer_calc", "XOR"))
        self.plusn.setText(_translate("Programmer_calc", "+n"))
        self.abs.setText(_translate("Programmer_calc", "|x|"))
        self.NOT.setText(_translate("Programmer_calc", "NOT"))
        self.log.setText(_translate("Programmer_calc", "log"))
        self.x_xx_y.setText(_translate("Programmer_calc", "x^y"))
        self.minusn.setText(_translate("Programmer_calc", "-n"))
        self.ones.setText(_translate("Programmer_calc", "ones"))
        self.int_2.setText(_translate("Programmer_calc", "int"))
        self.x_xx_1.setText(_translate("Programmer_calc", "x^-1"))
        self.twos.setText(_translate("Programmer_calc", "twos"))
        self.AND.setText(_translate("Programmer_calc", "AND"))
        self.variable_name.setItemText(0, _translate("Programmer_calc", "x"))
        self.log2.setText(_translate("Programmer_calc", "log2"))
        self.OR.setText(_translate("Programmer_calc", "OR"))
        self.shift_left.setItemText(0, _translate("Programmer_calc", "<<"))
        self.shift_right.setItemText(0, _translate("Programmer_calc", ">>"))
        self.aaaa.setText(_translate("Programmer_calc", "á"))
        self.fact.setText(_translate("Programmer_calc", "fact"))
        self.variable_name_2.setItemText(0, _translate("Programmer_calc", "32 bites"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    Programmer_calc = QtWidgets.QMainWindow()
    ui = Ui_Programmer_calc()
    ui.setupUi(Programmer_calc)
    Programmer_calc.show()
    sys.exit(app.exec_())
